# Generated by Django 2.1.3 on 2018-11-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ask_Gel0', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AddField(
            model_name='post',
            name='lieks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
