# Generated by Django 2.1.3 on 2018-11-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ask_Gel0', '0006_auto_20181105_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
