# Generated by Django 2.1.3 on 2018-11-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ask_Gel0', '0007_remove_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='answers',
            field=models.ManyToManyField(related_name='post_answers', to='Ask_Gel0.Answer'),
        ),
    ]
